### ISSUE TITLE
Links need to be updated 

### ISSUE THREAD

**Issue by vrysmart** [c-edw/ios-telemetry#5]
In your readme file you reference links ‘https://stan.sh/posts/dns-requests-of-ios-devices’ which no longer exists and is also in an unsecure domain. 
You also reference ‘https://cedwards.xyz/blog/ios-dns-privacy-investigation/’ which no longer exists either. Perhaps these links should be updated as they are of interest due to privacy concerns.

**Comment by c-edw** [comment]
Neither pages are served anymore, and there's not much I can do about the expired certificate because it isn't my site. I'll remove them both, thanks for bringing it to my attention.

**Comment by vrysmart** [comment]
Just so you know, your blog at ‘https://cedwards.xyz/’ is visible with its latest post listing dated April 26, 2019 (interesting post on ProtonMail).
Your other content might still be of interest to others. 🙂

**Comment by vrysmart** [comment]
Stan’s posting are not secure at (http://stan.sh/) and reflect his current projects in his world (which do not seem to include encryption or a social media; unless you include LinkedIn). 🌞

**Comment by c-edw** [comment]
Sorry, I'm not quite sure what you're pointing out, but I'm glad my blog is interesting for you (though I mostly write it to organise my thoughts rather than for an audience).
